openapi: 3.0.0
info:
  title: Pet Store API
  description: A simple pet store API
  version: 1.0.0
  contact:
    email: support@petstore.com
paths:
  /pets:
    get:
      summary: List all pets
      description: Returns a list of pets in the store
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: Maximum number of pets to return
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '500':
          description: Internal server error
          
    post:
      summary: Create a pet
      description: Adds a new pet to the store
      operationId: createPet
      tags:
        - pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
      responses:
        '201':
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /pets/{petId}:
    get:
      summary: Get pet by ID
      description: Returns a single pet by ID
      operationId: getPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: ID of the pet to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Pet found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
        '500':
          description: Internal server error

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - status
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: "Fluffy"
        species:
          type: string
          example: "Cat"
        age:
          type: integer
          minimum: 0
          example: 3
        status:
          type: string
          enum: [available, pending, sold]
          default: available
        
    NewPet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "Fluffy"
        species:
          type: string
          example: "Cat"
        age:
          type: integer
          minimum: 0
          example: 3
